### ISSUE TITLE
Color Palette displaying wrong color

### ISSUE THREAD

**Issue by nasnodkar** [HarshKhandeparkar/rainbow-board#13]
**Description**
When a user switches from line tool to normal brush or vice versa, the color of the brush goes back to the color of the tool which is expected but the selected color in the color palette stays the same as the old tool.

**To Reproduce**
1. Select line tool
2. Choose a color different from the brush tool
3. Switch back to brush tool
4. The color of brush will change, now open the color palette.
5. There you will see that the selected color is the color of the line tool and now the brush tool

**Expected behavior**
The selected color in the color palette should be of the color of the current tool and not the color which was chosen by the user the last time he opened it.

**Device Information:**
- Type: Desktop
 - OS: Windows 10 Home 64 bit
 - Version 0.7.0

**Comment by harshkhandeparkar** [comment]
Fixed on `main`. Will be released in `v0.7.0-rc.2`.
