### ISSUE TITLE
A Quick switch-to-previous-tool shortcut

### ISSUE THREAD

**Issue by nasnodkar** [HarshKhandeparkar/rainbow-board#14]
**Is your feature request related to a problem? Please describe.**
Currently to switch to the previous tool you were using , the only way is to use the ctrl + 1/2/3, which becomes quiet annoying when you have to switch multiple times.

**Describe the solution you'd like**
Instead I would love a shortcut like ctrl + space, to switch directly to the previous tool. It would ease the work of switching tools by a big margin.

**Comment by harshkhandeparkar** [comment]
Fixed on `main` branch. Will be released in v0.7.0-rc.2
