### ISSUE TITLE
macOS 0.4.0 Build

### ISSUE THREAD

**Issue by clnt** [HarshKhandeparkar/rainbow-board#2]
Hey @HarshKhandeparkar I came across this looking for a whiteboard app to use, assumed it should be pretty easy to build on macOS so gave it a go, this was built on macOS Mojave:

![Screenshot 2021-02-11 at 22 27 34](https://user-images.githubusercontent.com/19330442/107706896-ef546580-6cb8-11eb-9247-91b72f68e0ce.png)

Download link to DMG as it is 75mb: https://share.mattc.dev/Rainbow-Board-0.2.1.dmg.zip

Enjoy :)

Not sure how you are currently doing builds if manually or auto, but I have the ability to run a macOS VM on a server which could probably do something with a script.

**Comment by harshkhandeparkar** [comment]
Hi! Thank you so much!!
I actually do it manually because it is not so difficult for Linux and Windows.

I am not sure if the dmg metadata is correct, is it?

**Comment by harshkhandeparkar** [comment]
I will not have to change the code to show the dmg downloads :stuck_out_tongue:. Doing that now.

**Comment by harshkhandeparkar** [comment]
Added the asset to the GitHub release :heavy_check_mark:

**Comment by harshkhandeparkar** [comment]
Forge (a packaging tool used here) is supposed to be able to publish assets to GitHub but it is in beta and lacks some docs...

**Comment by harshkhandeparkar** [comment]
Added the link on the [website](https://harshkhandeparkar.github.io/rainbow-board). :heavy_check_mark: 
![image](https://user-images.githubusercontent.com/34770591/107749962-54539e00-6d41-11eb-98af-511c3e78d166.png)

**Comment by harshkhandeparkar** [comment]
![image](https://user-images.githubusercontent.com/34770591/107881192-4781a680-6f09-11eb-8a11-02b161fe3503.png)
I salute you.

**Comment by clnt** [comment]
@HarshKhandeparkar No problem :) Sorry bit busy at the moment so havent been able to reply properly. Just ran a quick build for you from latest, this time built on macOS Big Sur :)

https://share.mattc.dev/Rainbow-Board-0.3.4.dmg.zip

**Comment by harshkhandeparkar** [comment]
Thank you so much!

**Comment by harshkhandeparkar** [comment]
Uploaded :heavy_check_mark:

**Comment by clnt** [comment]
@HarshKhandeparkar Updated build: https://share.mattc.dev/Rainbow-Board-0.4.0.dmg.zip

Have you looked into using Travis CI at all to handle the builds for you?

**Comment by harshkhandeparkar** [comment]
> Updated build: https://share.mattc.dev/Rainbow-Board-0.4.0.dmg.zip

Thank you!

> Have you looked into using Travis CI at all to handle the builds for you?

I looked into Github actions but didn't get enough time to play with it...

**Comment by harshkhandeparkar** [comment]
I managed to build with actions :hot_face:
https://github.com/HarshKhandeparkar/rainbow-board/releases/tag/v0.4.0

Thank you for your help. Closing this issue now :)

**Comment by clnt** [comment]
@HarshKhandeparkar Awesome looks good, just downloaded and tested, its working well and feels much better to use already than 0.2.1 :)

No problem!
