### ISSUE TITLE
Gradient Brush

### ISSUE THREAD

**Issue by nasnodkar** [HarshKhandeparkar/rainbow-board#3]
I would like to see a gradient brush in Rainbow-Board. It would be cool to see one. If you are confused about what a gradient brush is , it is a brush which changed its color like a rainbow in a single stroke.
Here is an image for example. Thank You.
![image](https://user-images.githubusercontent.com/70008729/108616966-68318b00-7438-11eb-89f4-09aa0d8c5e2d.png)

**Comment by vivek-30** [comment]
@Cooldude069, @HarshKhandeparkar May be we can use hsl value for the strokeStyle of context of canvas. 😊

**Comment by harshkhandeparkar** [comment]
Actually, the backend is [here](https://github.com/HarshKhandeparkar/gpujs-real-renderer)

And we don't really use the canvas context directly :stuck_out_tongue:.

**Comment by harshkhandeparkar** [comment]
I don't really have time right now, but if you want to help, you can do so! :smile:

**Comment by vivek-30** [comment]
> Actually, the backend is [here](https://github.com/HarshKhandeparkar/gpujs-real-renderer)
> 
> And we don't really use the canvas context directly 😛.

ok i will look into this for further reference.

**Comment by vivek-30** [comment]
> I don't really have time right now, but if you want to help, you can do so! 😄

oh i can totally understand your situation. BTW @HarshKhandeparkar i am also a little busy but not as busy as you so if possible i will try to contribute to this incredible project 😊

**Comment by vivek-30** [comment]
Hi @HarshKhandeparkar i have tried  this and made a significant progress.but having some trouble with the code could you please help me? firstly i have created a gradient brush  in a dummy canvas.
see the demo -


https://user-images.githubusercontent.com/75980147/108699096-d787a780-752a-11eb-96f1-9f097665ee2f.mov


and tried to understand your code i did understand some part both of this repo as well as of `GPU real renderer` but still not getting how to make it happen.

**Comment by vivek-30** [comment]
Progress i have made in this code -

![Screenshot 2021-02-22 at 4 14 37 PM](https://user-images.githubusercontent.com/75980147/108697655-246a7e80-7529-11eb-921e-22c6a3993075.jpg)
![Screenshot 2021-02-22 at 4 14 45 PM](https://user-images.githubusercontent.com/75980147/108697669-2a605f80-7529-11eb-8b55-cc61214c158d.jpg)

**Comment by vivek-30** [comment]
i think i am struggling bcoz i am not familiar with typescript and electron , i know react and materialize csss but GPU real renderer is also becoming a hurdle for me 😅

**Comment by vivek-30** [comment]
Also if we want to add a new tool like this(gradient brush) we not only have to change code of this repo but also have to make adjustments in GPU real render as well , coz file like `tool.ts` will be responsible to shift to a new tool right?

**Comment by harshkhandeparkar** [comment]
Well, you will have to only change `gpujs-real-renderer`.

**Comment by harshkhandeparkar** [comment]
Do you understand how [gpu.js](https://gpu.rocks) works? :sweat_smile: 
You cannot use the canvas API directly for this.
Refer to these files:
https://github.com/HarshKhandeparkar/gpujs-real-renderer/blob/master/src/renderers/RealDrawBoard/tools/tools.ts
https://github.com/HarshKhandeparkar/gpujs-real-renderer/blob/master/src/renderers/RealDrawBoard/tools/brush.ts
and https://github.com/HarshKhandeparkar/gpujs-real-renderer/blob/b6332290954861d7f36afe6640a071d52659686b/src/renderers/RealDrawBoard/RealDrawBoard.ts#L102-L169

You will have to add another tool similar to these :)

**Comment by harshkhandeparkar** [comment]
I will handle the react and electron part of it, the gradient brush is only related to the [backend](https://github.com/HarshKhandeparkar/gpujs-real-renderer/). If there are any changes to the backend, I just make changes to the library `gpujs-real-renderer` on npm and then just update it here.
So to add a gradient brush, this repo is of no use.

**Comment by harshkhandeparkar** [comment]
Btw, if you want to discuss this further, you can message me on gitter or discord if you use it. (preferably discord)

**Comment by vivek-30** [comment]
> Do you understand how [gpu.js](https://gpu.rocks) works? 😅
> You cannot use the canvas API directly for this.
> Refer to these files:
> https://github.com/HarshKhandeparkar/gpujs-real-renderer/blob/master/src/renderers/RealDrawBoard/tools/tools.ts
> https://github.com/HarshKhandeparkar/gpujs-real-renderer/blob/master/src/renderers/RealDrawBoard/tools/brush.ts
> and https://github.com/HarshKhandeparkar/gpujs-real-renderer/blob/b6332290954861d7f36afe6640a071d52659686b/src/renderers/RealDrawBoard/RealDrawBoard.ts#L102-L169
> 
> You will have to add another tool similar to these :)

Honestly speaking i don't know anything about this 😂 but will try to understand it.for now please give me some time to digest this gigantic code😅

**Comment by vivek-30** [comment]
> Btw, if you want to discuss this further, you can message me on gitter or discord if you use it. (preferably discord)

Sure if i will need some help i will ask you through discord

**Comment by harshkhandeparkar** [comment]
I can make a server and invite you, one minute.

**Comment by vivek-30** [comment]
Thanku so much for your precious time and help ❤️. Means a lot to me😊

**Comment by harshkhandeparkar** [comment]
https://discord.gg/6GBeWRrg

**Comment by vivek-30** [comment]
> https://discord.gg/6GBeWRrg

sorry for the late response i got busy with some other stuff . oops it seems that this link has been expired. could you pease share a new one.

**Comment by harshkhandeparkar** [comment]
> > https://discord.gg/6GBeWRrg
> 
> sorry for the late response i got busy with some other stuff . oops it seems that this link has been expired. could you pease share a new one.

@vivek-30 A new one is in the readme :) click on the badge.

**Comment by harshkhandeparkar** [comment]
> Thanku so much for your precious time and help ❤️. Means a lot to me😊

Thank **you**!

**Comment by vivek-30** [comment]
@HarshKhandeparkar still unable to join 😞
![Screenshot 2021-02-22 at 10 31 45 PM](https://user-images.githubusercontent.com/75980147/108742629-e3d92800-755d-11eb-988e-f330e628913a.jpg)

**Comment by harshkhandeparkar** [comment]
Looks like someone deleted the link 😓 

https://discord.gg/fxrT2UW8 try this one.
