### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by harshkhandeparkar** [HarshKhandeparkar/rainbow-board#5]
**Describe the solution you'd like**
Zoom in and zoom out of the board.

**Comment by vivek-30** [comment]
By which mean you will prefer this functionality to achieve.

**Comment by vivek-30** [comment]
May be using some external module like hammer.js or by just using Vanilla js.

**Comment by vivek-30** [comment]
@HarshKhandeparkar ??

**Comment by harshkhandeparkar** [comment]
Vanilla is better. But the more important part is the backend :sweat_smile:

**Comment by vivek-30** [comment]
> Vanilla is better. But the more important part is the backend 😅

is that means, we still have to make changes in the `gpu-real-renderer`? 🧐

**Comment by harshkhandeparkar** [comment]
Yes :cold_sweat:

**Comment by vivek-30** [comment]
> Yes 😰

ok then 👍🏻

**Comment by Crimson-Blade** [comment]
If you guys are implementing a zoom feature, it'll be great if an output though .svg was added as well, along side .png

**Comment by harshkhandeparkar** [comment]
SVGs are complicated. They are not defined by pixels whereas rainbow board's canvas is.

**Comment by Crimson-Blade** [comment]
Oh, in that case it's fine. Just thought it'd be a nice to have.

**Comment by harshkhandeparkar** [comment]
It would definitely be nice to have! What do you think about converting png to svg? :thinking:

**Comment by harshkhandeparkar** [comment]
Partially fixed: Ctrl + scroll to zoom and Ctrl + drag to pan.

**Comment by harshkhandeparkar** [comment]
fixed in https://github.com/harshkhandeparkar/rainbow-board/releases/tag/v0.7.1
